<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function articlelist()
    {
        $queryBuilder = $this->createQueryBuilder('a');

        $queryBuilder->orderBy('a.date', 'ASC');
     
        return $queryBuilder
            ->getQuery()
            ->getResult();
    }
}
