<?php

namespace AppBundle\Repository;

/**
 * CommentaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCom($article)
    {
        $queryBuilder = $this->createQueryBuilder('c')
        //we made a juncture with the tricks entity alias trk
            ->innerJoin('c.article', 'art')
            ->addSelect('art')
            ->where('art = :articleid')
                ->setParameter('articleid' , $article)
            ->orderBy('c.id', 'DESC');
        
            return $queryBuilder
            ->getQuery()
            ->getResult();
    }
}
